In [2]:
# Đích đến để so sánh độ chính xác
GOAL = (1, 2, 3, 4, 5, 6, 7, 8, 0)

def print_board(state):
    for i in range(0, 9, 3):
        print(f"{state[i]} {state[i+1]} {state[i+2]}")
    print("-" * 10)

# 1. Hàm đếm xem có bao nhiêu số đang đứng đúng vị trí
def count_correct_positions(state):
    count = 0
    for i in range(9):
        # Không đếm số 0 (ô trống) vì ta chỉ cần các số từ 1-8 đúng vị trí
        if state[i] != 0 and state[i] == GOAL[i]:
            count += 1
    return count

# 2. Hàm tìm các trạng thái có thể đi tiếp
def get_neighbors(state):
    neighbors = []
    zero_index = state.index(0)
    row, col = divmod(zero_index, 3)
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)] # Lên, Xuống, Trái, Phải

    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_zero_index = new_row * 3 + new_col
            new_state = list(state)
            new_state[zero_index], new_state[new_zero_index] = new_state[new_zero_index], new_state[zero_index]
            neighbors.append(tuple(new_state))
    return neighbors

# --- CHƯƠNG TRÌNH CHÍNH ---

# Nhập dữ liệu từ bàn phím
print("Nhap day so (9 so tu 0-8, cach nhau bang dau cach):")
# Ví dụ nhập: 1 2 3 0 4 6 7 5 8
input_data = input().split()
start_state = tuple(int(x) for x in input_data)

current_state = start_state
history = [current_state] # Lưu lịch sử các bước đã đi

print("\nBat dau qua trinh di chuyen :")
print_board(current_state)

while True:
    neighbors = get_neighbors(current_state)
    
    best_neighbor = None
    max_correct = -1
    
    # Tìm trong các hàng xóm, cái nào có nhiều số đúng vị trí nhất
    for neighbor in neighbors:
        correct_count = count_correct_positions(neighbor)
        if correct_count > max_correct:
            max_correct = correct_count
            best_neighbor = neighbor
            
    # Nếu di chuyển tốt nhất dẫn đến một trạng thái đã từng đi qua -> Thoát
    if best_neighbor in history:
        print("PHAT HIEN LAP LAI TRANG THAI CU. DUNG CHUONG TRINH.")
        print(f"Trang thai bi lap: {best_neighbor}")
        break
    
    # Cập nhật trạng thái hiện tại
    current_state = best_neighbor
    history.append(current_state)
    
    print(f"Buoc tiep theo (Co {max_correct} so dung vi tri):")
    print_board(current_state)

    # Nếu đã đạt đến đích thì cũng dừng
    if current_state == GOAL:
        print("DA DAT DEN TRANG THAI DICH!")
        break

Nhap day so (9 so tu 0-8, cach nhau bang dau cach):

Bat dau qua trinh di chuyen :
1 2 3
4 5 0
6 7 8
----------
Buoc tiep theo (Co 5 so dung vi tri):
1 2 3
4 5 8
6 7 0
----------
PHAT HIEN LAP LAI TRANG THAI CU. DUNG CHUONG TRINH.
Trang thai bi lap: (1, 2, 3, 4, 5, 0, 6, 7, 8)


In [33]:

import random
import numpy as np
x,y = random.randint(1,9), random.randint(1,9)
state = [x,y]
def simple_reflex(state):
    n = int(input("nhap so dong va cot: "))
    goal = [0] * n 
    matrix = np.random.randint(0,2,size= (n,n))
    while state == 1:
        for i in random.randint(1, n-2):
            for j in random.randint(1, n-2):
                if state == [i,j]:
                    random(i-1, i+2), random(j-1, j+2) # Di chuyển ngẫu nhiên xung quanh vị trí hiện tại
                
        if state == [0,0]:
            random(state==[0,1], state==[1,0])
        if state == [0,n-1]:
            random(state==[0,n-2], state == [1,n-1])
        if state == [n-1,0]:
            random(state==[n-2,0], state == [n-1,1])
        if state == [n-1,n-1]:
            random(state==[n-2,n-1], state == [n-1,n-2])
        for i in random.randint(1,n-1):
            if state == [i,0]:
                random(state==[i-1,0], state == [i+1,0], state == [i,1])
            if state == [i,n-1]:
                random(state==[i-1,n-1], state == [i+1,n-1], state == [i,n-2])  
            if state == [0,i]:
                random(state==[0,i-1], state == [0,i+1], state == [1,i])
            if state == [n-1,i]:
                random(state==[n-1,i-1], state == [n-1,i+1], state == [n-2,i])
    state = 0
    print(matrix)
simple_reflex(state)
   
    



                    
         

    


[[0 1 0 1]
 [1 1 1 0]
 [1 1 0 1]
 [1 0 0 1]]


In [1]:
import random
import numpy as np

def simple_reflex():
    n = int(input("nhap so dong va cot: "))
    
    # Khởi tạo ma trận và vị trí ngẫu nhiên
    matrix = np.random.randint(0, 2, size=(n, n))
    x, y = random.randint(0, n-1), random.randint(0, n-1)
    state = [x, y]
    
    print("Ma trận ban đầu:\n", matrix)
    print(f"Vị trí bắt đầu: {state}")

    # Giả sử robot chạy trong 10 bước để làm sạch
    for _ in range(10):
        r, c = state[0], state[1]
        
        # 1. Kiểm tra và làm sạch tại chỗ
        if matrix[r][c] == 1:
            print(f"Tại {state}: Có rác! Đang hút...")
            matrix[r][c] = 0
        else:
            print(f"Tại {state}: Sạch.")

        # 2. Logic di chuyển ngẫu nhiên (Láng giềng)
        neighbors = []
        if r > 0: neighbors.append([r-1, c])     # Lên
        if r < n-1: neighbors.append([r+1, c])   # Xuống
        if c > 0: neighbors.append([r, c-1])     # Trái
        if c < n-1: neighbors.append([r, c+1])   # Phải
        
        state = random.choice(neighbors) # Cập nhật vị trí mới

    print("\nMa trận sau khi làm sạch:\n", matrix)

simple_reflex()

Ma trận ban đầu:
 [[0 1 0 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 0 1 0]]
Vị trí bắt đầu: [0, 2]
Tại [0, 2]: Sạch.
Tại [0, 3]: Sạch.
Tại [0, 2]: Sạch.
Tại [0, 3]: Sạch.
Tại [0, 2]: Sạch.
Tại [0, 1]: Có rác! Đang hút...
Tại [1, 1]: Sạch.
Tại [0, 1]: Sạch.
Tại [0, 2]: Sạch.
Tại [0, 1]: Sạch.

Ma trận sau khi làm sạch:
 [[0 0 0 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 0 1 0]]
