- máy hút bụi 
P: hàm đánh giá độ bẩn và ưu tiên dọn các ô bẩn trước
E: là một ma trận mxn có các số 0,1 để biểu hiện 0 là sạch và 1 là còn bẩn
A: hàm để agent thực hiện hành động
S: cảm biến giúp agent nhận biết môi trường xung quanh


https://github.com/Ngxuannhatt/AI.git

In [ ]:
import random
import numpy as np

# Nhập kích thước
n = int(input("Nhập số dòng và cột: "))

def simple_reflex(n):
    # Khởi tạo ma trận ngẫu nhiên: 0 (sạch), 1 (rác), 2 (vật cản)
    matrix = np.random.randint(0, 3, size=(n, n))
    
    # Tìm một vị trí bắt đầu không phải là vật cản (số 2)
    possible_starts = np.argwhere(matrix != 2)
    if len(possible_starts) == 0:
        print("Ma trận toàn vật cản!")
        return
    
    start_pos = random.choice(possible_starts)
    state = [start_pos[0], start_pos[1]]
    
    print("Ma trận ban đầu (0: sạch, 1: rác, 2: vật cản):")
    print(matrix)
    print(f"Vị trí bắt đầu: {state}")
    print("-" * 30)
    history = set()
    history.add(tuple(state))
    steps = 0
    # Chừng nào còn rác (số 1)
    while np.any(matrix == 1):
        r, c = state[0], state[1]
        
        # 1. HÀNH ĐỘNG (Kiểm tra tại chỗ)
        if matrix[r][c] == 1:
            matrix[r][c] = 0
            print(f"[{steps}] Hút rác tại: [{r}, {c}]")
            print (matrix)
        elif matrix[r][c] == 0:
            print(f"[{steps}] Sạch rồi tại: [{r}, {c}]")
            print(matrix)
       
        
        # 2. DI CHUYỂN (Tìm ô lân cận hợp lệ)
        neighbors = []
        # Kiểm tra 4 hướng: Lên, Xuống, Trái, Phải
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            # Điều kiện: Trong biên và KHÔNG phải vật cản (khác 2)
            if 0 <= nr < n and 0 <= nc < n and matrix[nr][nc] != 2:
                neighbors.append([nr, nc])
        valid_neighbors = [n for n in neighbors if n not in history]
        if valid_neighbors:
            state = random.choice(valid_neighbors)
            print(f"Di chuyển đến: {state}")
        elif neighbors:
            print(" da het o moi")
    
        else:
            print("Robot bị kẹt giữa các vật cản!")
            break
        history.add(tuple(state))
            
        steps += 1
        if steps > 100: # Giới hạn để tránh lặp vô tận nếu rác bị bao vây bởi vật cản
            print("Quá thời gian (có thể rác nằm ở khu vực không thể tiếp cận)")
            break

    print("-" * 30)
    print("Kết quả cuối cùng:")
    print(matrix)
    print(history)
simple_reflex(n)

Ma trận ban đầu (0: sạch, 1: rác, 2: vật cản):
[[2 2 1]
 [2 0 0]
 [0 2 1]]
Vị trí bắt đầu: [np.int64(1), np.int64(2)]
------------------------------
[0] Sạch rồi tại: [1, 2]
[[2 2 1]
 [2 0 0]
 [0 2 1]]
Di chuyển đến: [np.int64(2), np.int64(2)]
[1] Hút rác tại: [2, 2]
[[2 2 1]
 [2 0 0]
 [0 2 0]]
Di chuyển đến: [np.int64(1), np.int64(2)]
[2] Sạch rồi tại: [1, 2]
[[2 2 1]
 [2 0 0]
 [0 2 0]]
Di chuyển đến: [np.int64(2), np.int64(2)]
[3] Sạch rồi tại: [2, 2]
[[2 2 1]
 [2 0 0]
 [0 2 0]]
Di chuyển đến: [np.int64(1), np.int64(2)]
[4] Sạch rồi tại: [1, 2]
[[2 2 1]
 [2 0 0]
 [0 2 0]]
Di chuyển đến: [np.int64(0), np.int64(2)]
[5] Hút rác tại: [0, 2]
[[2 2 0]
 [2 0 0]
 [0 2 0]]
Di chuyển đến: [np.int64(1), np.int64(2)]
------------------------------
Kết quả cuối cùng:
[[2 2 0]
 [2 0 0]
 [0 2 0]]
[(np.int64(1), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(2), np.int64(2)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(2))]


In [ ]:
from collections import deque
from node import Node

def ids_1(self):
    limit = 0
    while True:
        result, status = depth_limited_search(self, limit) # Đã fix lỗi 1
        
        if status == "SUCCESS":
            return result      
        elif status == "FAIL":
            return None        
        elif status == "OVERLOAD":  # Bắt thêm trạng thái quá tải
            print("Thuật toán quá tải, buộc dừng hoàn toàn.")
            return None
        
        # Nếu status == "CUTOFF" thì mới tăng độ sâu
        limit += 1

def depth_limited_search(self,limit):
    """
    Hàm tìm kiếm theo chiều sâu giới hạn (DLS) 
    CHUYẨN ĐỔI HOÀN TOÀN SANG KIỂM TRA MUỘN (LATE TEST)
    """
    root_node = Node(self.agent_x, self.agent_y, self.matrix, parent=None, action=f"Bắt đầu tại ({self.agent_x},{self.agent_y})")
    root_node.depth = 0 
    
    # Sử dụng danh sách (list) như một Stack (LIFO) cho DFS
    frontier = [root_node]
    
    # Tập lưu vết: Trạng thái -> Độ sâu nhỏ nhất từng duyệt qua
    reached_at_depth = {} 
    
    cutoff_occurred = False
    steps_limit = 0

    while frontier:
        curr = frontier.pop()  # LẤY RA TỪ CUỐI STACK (LIFO)
        steps_limit += 1
        
        # --- BẮT ĐẦU KIỂM TRA MUỘN (LATE TEST) ---
        
        # A. Kiểm tra trùng lặp trạng thái (Late State Checking)
        state_key = curr.get_state_key()
        if state_key in reached_at_depth and reached_at_depth[state_key] <= curr.depth:
            continue  # Đã từng duyệt trạng thái này ở tầng nông hơn -> Bỏ qua không xử lý tiếp
        
        # Nếu chưa duyệt hoặc duyệt ở tầng sâu hơn (tối ưu hơn), ghi nhận lại độ sâu mới
        reached_at_depth[state_key] = curr.depth

        # B. Kiểm tra đích muộn (Late Goal Test)
        if curr.is_goal():
            path = []
            temp = curr
            while temp is not None:
                path.append(temp)
                temp = temp.parent
            path.reverse()
            return path, "SUCCESS"
        
        # C. Kiểm tra giới hạn độ sâu (Late Cutoff Test)
        if curr.depth >= limit:
            cutoff_occurred = True
            continue  # Chạm giới hạn tầng, không sinh con nữa
            
        # --- KẾT THÚC KIỂM TRA MUỘN ---

        r, c = curr.x, curr.y
        
        # --- SINH CÁC NODE CON (Nạp vô điều kiện vào Frontier) ---
        
        # 1. Hành động DI CHUYỂN
        # Duyệt theo thứ tự này để khi POP ra (LIFO) robot sẽ ưu tiên hướng đi hợp lý
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < self.n and 0 <= nc < self.n:
                child_node = Node(nr, nc, curr.matrix, parent=curr, action=f"Đi tới ({nr},{nc})")
                child_node.depth = curr.depth + 1
                frontier.append(child_node)  # Nạp thẳng vào frontier theo đúng chuẩn Late Test
                
        # 2. Hành động HÚT (Nạp vào sau cùng để được POP ra trước)
        if curr.matrix[r][c] == 1:
            new_mat = [row[:] for row in curr.matrix]
            new_mat[r][c] = 0
            child_node = Node(r, c, new_mat, parent=curr, action=f"Hút rác tại ({r},{c})")
            child_node.depth = curr.depth + 1
            frontier.append(child_node)  # Nạp thẳng vào frontier theo đúng chuẩn Late Test
        
        # Cơ chế khẩn cấp ngăn treo UI nếu không gian trạng thái quá lớn
        if steps_limit > 300000:
            print("Đã duyệt quá nhiều bước ở tầng này. Ép cắt tầng để bảo vệ UI.")
            return None, "OVERLOAD"  # Đổi từ CUTOFF thành OVERLOAD
            
    if cutoff_occurred:
        return None, "CUTOFF"
    else:
        return None, "FAIL"