- máy hút bụi 
P: hàm đánh giá độ bẩn và ưu tiên dọn các ô bẩn trước
E: là một ma trận mxn có các số 0,1 để biểu hiện 0 là sạch và 1 là còn bẩn
A: hàm để agent thực hiện hành động
S: cảm biến giúp agent nhận biết môi trường xung quanh


https://github.com/Ngxuannhatt/AI.git

In [2]:
import random
import numpy as np

# Nhập kích thước
n = int(input("Nhập số dòng và cột: "))

def simple_reflex(n):
    # Khởi tạo ma trận ngẫu nhiên: 0 (sạch), 1 (rác), 2 (vật cản)
    matrix = np.random.randint(0, 3, size=(n, n))
    
    # Tìm một vị trí bắt đầu không phải là vật cản (số 2)
    possible_starts = np.argwhere(matrix != 2)
    if len(possible_starts) == 0:
        print("Ma trận toàn vật cản!")
        return
    
    start_pos = random.choice(possible_starts)
    state = [start_pos[0], start_pos[1]]
    
    print("Ma trận ban đầu (0: sạch, 1: rác, 2: vật cản):")
    print(matrix)
    print(f"Vị trí bắt đầu: {state}")
    print("-" * 30)

    steps = 0
    # Chừng nào còn rác (số 1)
    while np.any(matrix == 1):
        r, c = state[0], state[1]
        
        # 1. HÀNH ĐỘNG (Kiểm tra tại chỗ)
        if matrix[r][c] == 1:
            matrix[r][c] = 0
            print(f"[{steps}] Hút rác tại: [{r}, {c}]")
            print (matrix)
        elif matrix[r][c] == 0:
            print(f"[{steps}] Sạch rồi tại: [{r}, {c}]")
            print(matrix)
        # 2. DI CHUYỂN (Tìm ô lân cận hợp lệ)
        neighbors = []
        # Kiểm tra 4 hướng: Lên, Xuống, Trái, Phải
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            # Điều kiện: Trong biên và KHÔNG phải vật cản (khác 2)
            if 0 <= nr < n and 0 <= nc < n and matrix[nr][nc] != 2:
                neighbors.append([nr, nc])
        
        if neighbors:
            state = random.choice(neighbors)
            print(f"Di chuyển đến: {state}")
        else:
            print("Robot bị kẹt giữa các vật cản!")
            break
            
        steps += 1
        if steps > 100: # Giới hạn để tránh lặp vô tận nếu rác bị bao vây bởi vật cản
            print("Quá thời gian (có thể rác nằm ở khu vực không thể tiếp cận)")
            break

    print("-" * 30)
    print("Kết quả cuối cùng:")
    print(matrix)

simple_reflex(n)

Ma trận ban đầu (0: sạch, 1: rác, 2: vật cản):
[[1 1 2]
 [2 0 1]
 [2 2 1]]
Vị trí bắt đầu: [np.int64(2), np.int64(2)]
------------------------------
[0] Hút rác tại: [2, 2]
[[1 1 2]
 [2 0 1]
 [2 2 0]]
Di chuyển đến: [np.int64(1), np.int64(2)]
[1] Hút rác tại: [1, 2]
[[1 1 2]
 [2 0 0]
 [2 2 0]]
Di chuyển đến: [np.int64(1), np.int64(1)]
[2] Sạch rồi tại: [1, 1]
[[1 1 2]
 [2 0 0]
 [2 2 0]]
Di chuyển đến: [np.int64(0), np.int64(1)]
[3] Hút rác tại: [0, 1]
[[1 0 2]
 [2 0 0]
 [2 2 0]]
Di chuyển đến: [np.int64(0), np.int64(0)]
[4] Hút rác tại: [0, 0]
[[0 0 2]
 [2 0 0]
 [2 2 0]]
Di chuyển đến: [np.int64(0), np.int64(1)]
------------------------------
Kết quả cuối cùng:
[[0 0 2]
 [2 0 0]
 [2 2 0]]
