In [7]:
import random
import numpy as np

# Khởi tạo n trước để dùng cho x, y
n = int(input("nhap so dong va cot: "))
x, y = random.randint(0, n-1), random.randint(0, n-1)
state = [x, y]

def simple_reflex(state, n):
    # Tạo ma trận ngẫu nhiên 0, 1
    matrix = np.random.randint(0, 2, size=(n, n))
    print("Ma trận ban đầu:\n", matrix)
    print(f"Vị trí bắt đầu: {state}")

    # Chừng nào ma trận còn rác (số 1)
    while np.any(matrix == 1):
        r, c = state[0], state[1]

        # 1. Hành động: Nếu có rác thì hút
        if matrix[r][c] == 1:
            matrix[r][c] = 0
            print(f"Hút rác tại: [{r}, {c}]")

        # 2. Logic di chuyển dựa trên khung của bạn
        # Trường hợp 1: Ở giữa (không chạm biên)
        if 1 <= r <= n-2 and 1 <= c <= n-2:
            state = random.choice([[r-1, c], [r+1, c], [r, c-1], [r, c+1]])

        # Trường hợp 2: Các góc
        elif state == [0, 0]:
            state = random.choice([[0, 1], [1, 0]])
        elif state == [0, n-1]:
            state = random.choice([[0, n-2], [1, n-1]])
        elif state == [n-1, 0]:
            state = random.choice([[n-2, 0], [n-1, 1]])
        elif state == [n-1, n-1]:
            state = random.choice([[n-2, n-1], [n-1, n-2]])

        # Trường hợp 3: Các cạnh (biên)
        else:
            if c == 0: # Cạnh trái
                state = random.choice([[r-1, 0], [r+1, 0], [r, 1]])
            elif c == n-1: # Cạnh phải
                state = random.choice([[r-1, n-1], [r+1, n-1], [r, n-2]])
            elif r == 0: # Cạnh trên
                state = random.choice([[0, c-1], [0, c+1], [1, c]])
            elif r == n-1: # Cạnh dưới
                state = random.choice([[n-1, c-1], [n-1, c+1], [n-2, c]])
        print(matrix)
        print("-" * 30)
    print("\nMa trận đã sạch:\n", matrix)
simple_reflex(state, n)

Ma trận ban đầu:
 [[0 0 0]
 [1 0 1]
 [1 0 0]]
Vị trí bắt đầu: [1, 1]
[[0 0 0]
 [1 0 1]
 [1 0 0]]
------------------------------
[[0 0 0]
 [1 0 1]
 [1 0 0]]
------------------------------
Hút rác tại: [2, 0]
[[0 0 0]
 [1 0 1]
 [0 0 0]]
------------------------------
Hút rác tại: [1, 0]
[[0 0 0]
 [0 0 1]
 [0 0 0]]
------------------------------
[[0 0 0]
 [0 0 1]
 [0 0 0]]
------------------------------
[[0 0 0]
 [0 0 1]
 [0 0 0]]
------------------------------
[[0 0 0]
 [0 0 1]
 [0 0 0]]
------------------------------
Hút rác tại: [1, 2]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
------------------------------

Ma trận đã sạch:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


- máy hút bụi 
P: hàm đánh giá độ bẩn và ưu tiên dọn các ô bẩn trước
E: là một ma trận mxn có các số 0,1 để biểu hiện 0 là sạch và 1 là còn bẩn
A: hàm để agent thực hiện hành động
S: cảm biến giúp agent nhận biết môi trường xung quanh


https://github.com/Ngxuannhatt/AI.git